#!/usr/bin/env python3
"""For each of the 10 known CSR D1-vs-D2 field collisions, classify each
differing script slot as:

  - d1-only-edited / d2-only-edited: the OTHER disc's CSR script == pristine
    for that slot -> no collision, just take the edited side (WHITE2 pattern).
  - superset: one side's op stream is the other's with pure insertions
    (SequenceMatcher opcodes are only 'equal'/'insert') -> safe to take the
    superset side, nothing is lost.
  - rework: same slot edited differently on both sides (replace/delete
    present) -> NOT safely auto-mergeable; needs manual Makou judgement.

Usage:
  python3 scripts/analyze_collision_mergeability.py -o /tmp/mergeability.md
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from disc_sources import load_csr_image, load_pristine_image  # noqa: E402
from field_dat import load_field_dat  # noqa: E402
from psx_mode2_iso import extract_file  # noqa: E402

FIELDS = [
    "BLACKBGB", "BUGIN1A", "COS_BTM", "COS_BTM2", "DEL1",
    "JUNAIR2", "LOST2", "NIVGATE", "RCKTIN2", "RCKTIN7",
]


def slot_map(dat_bytes: bytes) -> dict[tuple[str, int], bytes]:
    fd = load_field_dat(dat_bytes)
    return {(s.entity, s.slot): s.raw for s in fd.scripts}


def classify_slot(a: bytes | None, b: bytes | None) -> str:
    if a == b:
        return "same"
    if a is None:
        return "only-in-b"
    if b is None:
        return "only-in-a"
    sm = difflib.SequenceMatcher(a=a, b=b, autojunk=False)
    ops = {op for op, *_ in sm.get_opcodes()}
    ops.discard("equal")
    if ops <= {"insert"}:
        return "b-superset"
    if ops <= {"delete"}:
        return "a-superset"
    return "rework"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", type=Path, required=True)
    args = ap.parse_args()

    p1 = bytes(load_pristine_image(1))
    p2 = bytes(load_pristine_image(2))
    c1 = bytes(load_csr_image(1))
    c2 = bytes(load_csr_image(2))

    lines = [
        "# Mergeability classification for the 10 CSR D1 vs D2 field collisions",
        "",
        "Generated by `scripts/analyze_collision_mergeability.py`.",
        "",
    ]
    summary_rows = []
    for name in FIELDS:
        path = f"FIELD/{name}.DAT"
        d1 = extract_file(c1, path)
        d2 = extract_file(c2, path)
        pd1 = extract_file(p1, path)
        pd2 = extract_file(p2, path)
        d1_edited = d1 != pd1
        d2_edited = d2 != pd2

        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- CSR D1 edited vs pristine D1: **{d1_edited}**")
        lines.append(f"- CSR D2 edited vs pristine D2: **{d2_edited}**")

        if not d1_edited or not d2_edited:
            only = "D2" if not d1_edited else "D1"
            lines.append(f"- **Verdict: no collision — only {only} has real CSR edits. Take {only} verbatim.**")
            lines.append("")
            summary_rows.append((name, "no-collision", only, ""))
            continue

        map_a = slot_map(d1)
        map_b = slot_map(d2)
        keys = sorted(set(map_a) | set(map_b))
        per_slot = []
        worst = "same"
        order = ["same", "b-superset", "a-superset", "only-in-a", "only-in-b", "rework"]
        for k in keys:
            ra, rb = map_a.get(k), map_b.get(k)
            cls = classify_slot(ra, rb)
            if cls != "same":
                per_slot.append((k, cls))
            if order.index(cls) > order.index(worst):
                worst = cls
        lines.append(f"- Differing slots: {len(per_slot)}")
        for k, cls in per_slot:
            lines.append(f"  - `{k[0]}` slot {k[1]}: `{cls}`")
        if worst in ("b-superset",):
            verdict = "safe auto-merge: take D2 (superset of D1) for all slots"
        elif worst in ("a-superset",):
            verdict = "safe auto-merge: take D1 (superset of D2) for all slots"
        elif worst == "same":
            verdict = "no real script diff after slot compare (should not happen)"
        else:
            verdict = "MANUAL REVIEW — rework/only-in-one-side slots present, cannot blind-merge"
        lines.append(f"- **Verdict: {verdict}**")
        lines.append("")
        summary_rows.append((name, worst, "", verdict))

    lines2 = ["# Summary", "", "| Field | Worst slot class | Verdict |", "|---|---|---|"]
    for name, worst, only, verdict in summary_rows:
        v = f"take {only} (no collision)" if only else verdict
        lines2.append(f"| {name} | {worst} | {v} |")
    args.output.write_text("\n".join(lines2 + [""] + lines), encoding="utf-8")
    print(f"Wrote {args.output}")
    for name, worst, only, verdict in summary_rows:
        print(f"{name}: worst={worst} verdict={'take '+only if only else verdict}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
